{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-IN",
    "dataSources": [
      {
        "type": "structured",
        "name": "File/C:\\Users\\7000027272\\Desktop\\DataForGit xlsx",
        "connectionDetails": {
          "protocol": "file",
          "address": {
            "path": "C:\\Users\\7000027272\\Desktop\\DataForGit.xlsx"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "kind": "File",
          "path": "c:\\users\\7000027272\\desktop\\dataforgit.xlsx"
        },
        "contextExpression": [
          "let",
          "    #\"0001\" = Excel.Workbook(..., null, true)",
          "in",
          "    #\"0001\""
        ]
      }
    ],
    "tables": [
      {
        "name": "Sheet1",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"File/C:\\Users\\7000027272\\Desktop\\DataForGit xlsx\",",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data]",
                "in",
                "    Sheet1_Sheet"
              ]
            }
          }
        ]
      },
      {
        "name": "Sheet11",
        "columns": [
          {
            "name": "Data",
            "dataType": "int64",
            "sourceColumn": "Data"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"File/C:\\Users\\7000027272\\Desktop\\DataForGit xlsx\",",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Data\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "NewVersion",
        "columns": [
          {
            "name": "Data",
            "dataType": "int64",
            "sourceColumn": "Data"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"File/C:\\Users\\7000027272\\Desktop\\DataForGit xlsx\",",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Data\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}